### ISSUE TITLE
Remove javadoc warnings from generated RPC services

### ISSUE THREAD

**Issue by LeovR** [gwt-maven-plugin/gwt-maven-plugin#100]
Currently, `generateAsync` does not generate `@param` and `@return` tags in the javadoc's section corresponding to the generated methods.
This generates warnings.

**Comment by ibaca** [comment]
FYI I have created a project to generate RPC async interfaces using annotation processors. This plugin copies javadocs from the service interface into the async one. Although it do not make any transformation, so you will have those warning for the async parm.
https://github.com/intendia-oss/autorpc-gwt

Closing this anyway. Sorry.
