### ISSUE TITLE
Feature to avoid "Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock."

### ISSUE THREAD

**Issue by mrietveld** [gwt-maven-plugin/gwt-maven-plugin#106]
One of the issues we ran up against with a number of our long-running gwt-maven-plugin compile (jenkins) jobs was that the default Java preferences factory (and the rest of that code) would run into file lock problems because of the length of the compile process. 

For example: 

```
[ERROR] Nov 19, 2014 6:12:49 PM java.util.prefs.FileSystemPreferences syncWorld
[ERROR] WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
[ERROR] Nov 19, 2014 6:13:22 PM java.util.prefs.FileSystemPreferences syncWorld
[ERROR] WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
```

There's a decent analysis/write-up of the problem [here](http://allaboutbalance.com/articles/disableprefs/). 

It would be easy enough to add an option to the gwt-maven-plugin compile mojo to avoid this problem. 

I will submit a pull request after submitting this issue with one approach to fixing this problem. 

Thanks!

**Comment by wkok** [comment]
@mrietveld Have you found a solution to this?

**Comment by mrietveld** [comment]
@wkok No, I don't think I did. You could solve it by submitting a PR here to deal with it.

**Comment by bric3** [comment]
> This has to do with the fact that the syncWorld() method is called from a static initializer block: see [this article](https://github.com/gwt-maven-plugin/gwt-maven-plugin/issues/allaboutbalance.com/articles/disableprefs/) for more information.

FYI the site is dead: here's the archive.org (❤️) link: https://web.archive.org/web/20170704120035/allaboutbalance.com/articles/disableprefs/
