### ISSUE TITLE
Staleness check in CompileMojo needs to look at *.cache.{html,js} files too

### ISSUE THREAD

**Issue by tbroyer** [gwt-maven-plugin/gwt-maven-plugin#108]
See https://stackoverflow.com/a/27187142/116472

`gwt:run` and `gwt:run-codeserver` will overwrite the nocache.js with a dev-specific version, so if no change is made to the sources `gwt:compile` will think the output is up-to-date and will skip compilation, and the dev-specific nocache.js will be packaged/deployed.

`gwt:compile` should therefore check not only the nocache.js for staleness, but also the cache.js and/or cache.html. That could still lead to false-negatives (`gwt:compile` followed by `gwt:run` followed by `gwt:compile` again without any change in the sources will lead the second `gwt:compile` to skip compilation, leaving in the dev-specific nocache.js from the `gwt:run` execution) but will catch more cases.

Of course the real solution is for users to `mvn clean` or `mvn -Dgwt.compile.force …` when deploying/releasing. Or maybe we could just remove the staleness check and let users pass an explicit `-Dgwt.compiler.skip` when needed?

**Comment by ibaca** [comment]
I still think that this staleness check makes no sense, if you want to compile classes you run `mvn compile` if you want to package you run `mvn package` if you want to debug you run `mvn gwt:run-codeserver`, etc. This magic is probably derived (as most of this plugins problems) from mixing server and client code in the same module, so you end up compiling the whole app, so you try to optimize your compilation times with this checks. IMO if you want to compile the client, just launch a `mvn -am -pl :client package` and after that use only a `mvn -am -pl :server tomcat:run` or something similar, zero magic, works as expected. Really do not see the case that you want to execute a package and do not expect a new GWT compilation.

In any case I'm not going to apply any change, this plugin is pretty mature and I'll hope everyone is used to the current behaviour.
