### ISSUE TITLE
Spring security Java Config won't work in devmode.

### ISSUE THREAD

**Issue by tttomat19** [gwt-maven-plugin/gwt-maven-plugin#112]
http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#jc
I've tried to make an application with spring-security (basically this could be done without involving GWT) by spring-security manuals.
With Java config Application was working ok with autogenerated login etc. when running on non-embedded apache-tomcat-8.0.18 and not working in devmode.

Xml-based config works both in devmode and when running on non-embedded tomcat.
I would suggest this is somehow related to Jetty container used by plugin.

**Comment by branflake2267** [comment]
Instead of using dev mode, I'd suggest creating a generic java application with code server entry point. In the code server args, put a -launcherDir ./path/to/output/war and then the gwt project module. Then start the web server of your choice, then start the java application code server, then goto the web server url.

**Comment by branflake2267** [comment]
By the way, a Google Eclipse plugin Code Server launcher is in the works.

**Comment by kmthinkingrock** [comment]
Can this solution be applied to the GWTTestCase? I am having major issues with the inbuilt web-server, especially given that it has to be a specific version.

**Comment by ibaca** [comment]
Closing because the new gwt maven plugin (https://tbroyer.github.io/gwt-maven-plugin/migrating.html) is multi-module friendly, and this problem should be fixed splitting the project into a client and server modules.
