### ISSUE TITLE
Lack of documentation: codehaus is closed

### ISSUE THREAD

**Issue by andypower** [gwt-maven-plugin/gwt-maven-plugin#115]
Hi,
the documentation for Mojo's Maven Plugin for GWT is not available anymore. 
The  http://www.codehaus.org/ home page reports:
"All Codehaus services have now been terminated.
With increasing diversity in opensource hosting platforms like Github and Bitbucket - who are meeting the needs of 1000s of projects - it made sense to end the opensource hosting services of Codehaus. 
Codehaus has operated at a loss for several years now (we're not powered by venture capital), and could not compete with the army of developers and integrated product offerings that are now commonplace. "

Where we'll find the new documentation?

**Comment by mseddon** [comment]
I'm not sure if there's any official location at the moment, but hopefully @tbroyer and co are aware of this.

http://web.archive.org/web/20150510232623/http://mojo.codehaus.org/gwt-maven-plugin/ works as a stop-gap solution for now, but is far from ideal.

**Comment by andypower** [comment]
@mseddon Thank you for the tip!

**Comment by tbroyer** [comment]
Ideally, someone would push the website to http://www.mojohaus.org/gwt-maven-plugin, or possibly https://gwt-maven-plugin.github.io/gwt-maven-plugin/

See also: https://groups.google.com/d/topic/codehaus-mojo-gwt-maven-plugin-users/_WhNPQUNyd8
Feel free to volunteer.

**Comment by ibaca** [comment]
I did a pull request to deploy maven site to gwt-maven-plugin.github.io but I did not get any response :disappointed:.

**Comment by ibaca** [comment]
FYI :neckbeard: I just created this pull request https://github.com/mojohaus/mojohaus.github.io/pull/8 to redirect  http://www.mojohaus.org/gwt-maven-plugin to https://gwt-maven-plugin.github.io/gwt-maven-plugin/.

**Comment by ibaca** [comment]
Google returns https://gwt-maven-plugin.github.io/gwt-maven-plugin/ just finding 'gwt maven'…
![screen shot 2016-08-23 at 19 21 27](https://cloud.githubusercontent.com/assets/1042225/17902250/d8b73a1e-6966-11e6-9e5b-3ef2ac12d335.png)
