### ISSUE TITLE
Recursive module check up to date 

### ISSUE THREAD

**Issue by ksfreitas** [gwt-maven-plugin/gwt-maven-plugin#120]
Situation: a project have modules A and B and the Module A inherits the module B (without EntryPoint).

Steps:
1. In first compile, module A will be compiled (all fine here)
2. Change some java files in module B
3. Recompile (without clean)
4. The changes in module B are not detected by gwt-maven-plugin and the compilation is ignored (Nothing to compile - all classes are up to date)

**Comment by ibaca** [comment]
My recommendations :wink:  (choose one)
1. Use always gwt.compiler.force or gwt.compiler.skip
2. Use the new plugin https://github.com/tbroyer/gwt-maven-archetypes/ which is multimodule friendly
3. Understand exactly what's happening and solve your problem (if you find "gwt multimodule tbroyer" in google you will find a lot of posts to solve the problem, also old version of https://github.com/tbroyer/gwt-maven-archetypes contains example configurations, deep understanding on maven will help).

This is about multi-module problems. Also, there are a bug which might be causing your the problem too: https://github.com/gwt-maven-plugin/gwt-maven-plugin/issues/108.

**Comment by ibaca** [comment]
Duplicated #108.
