### ISSUE TITLE
GWT Compiler Issue - Lost communication Error

### ISSUE THREAD

**Issue by bchoddny** [gwt-maven-plugin/gwt-maven-plugin#121]
We came across this error in our build machine, recently. The error doesn't explicitly states any specific reason. I would like to find out if any one came across this, and if any resolution. Any help is appreciated

GWT 2.5.0
jdk1.7.25
gwt-maven-plugin 2.5.0

Maven GWT compile configuraiton

```				
                      <configuration>
					<workDir>${gwt.compile.workDir}</workDir>
					<extraJvmArgs>-Xmx1024m -Djava.io.tmpdir=${gwt.compile.workDir}</extraJvmArgs>
					<module>net.dds.idesk.financials.gwt.Application</module>
					<logLevel>TRACE</logLevel>
					<!-- URL that should be automatically opened in the GWT shell (gwt:run). -->
					<runTarget>index.html</runTarget>
					<!-- Location of the develop-mode web application structure (gwt:run). -->
					<hostedWebapp>target/www</hostedWebapp>
					<!-- Ask GWT to create the Story of Your Compile (SOYC) (gwt:compile) -->
					<soyc>false</soyc>
				</configuration>
```
06:00:16 [INFO] [INFO] Process output
06:00:16 [INFO] [INFO] Compiling
06:00:16 [INFO] [INFO] Compiling permutation 3...
06:02:29 [INFO] [INFO] [WARN] Lost communication with remote process
06:02:29 [INFO] [INFO] java.io.EOFException
06:02:29 [INFO] [INFO] at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2596)
06:02:29 [INFO] [INFO] at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1316)
06:02:29 [INFO] [INFO] at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
06:02:29 [INFO] [INFO] at com.google.gwt.dev.ExternalPermutationWorkerFactory$ExternalPermutationWorker.compile(Externa

**Comment by ibaca** [comment]
Sorry, I'm going to close this issue without response. I hope you had already solved that during this year. I think that stackoverflow or google groups usually is a better place to ask general questions or problems, and you create an issue when you find an actual bug or request for an improvement. In any case, if you still have this problem and think this is a gwt-maven-plugin problem do not hesitate to re-open the issue.
