### ISSUE TITLE
Specify jvm causes javac: invalid flag error

### ISSUE THREAD

**Issue by magick93** [gwt-maven-plugin/gwt-maven-plugin#122]
For detailed explaination, please see http://stackoverflow.com/questions/33037221/compiling-gwt-with-maven-specify-jvm/33037889.

When specifying the jvm in the configuration settings in the gwt-maven-plugin (version 2.7.0) then I get:

javac: invalid flag: -Xmx512m

**Comment by ibaca** [comment]
Sorry, not reproducible, did you still has this problem? doesn't look related to this plugin, but if you has a repo case add a link here.
