### ISSUE TITLE
Support for -generateJsInteropExports

### ISSUE THREAD

**Issue by bitwerk** [gwt-maven-plugin/gwt-maven-plugin#123]
It seems jsInteropMode has been replaced by generateJsInteropExports, but this option seems unsupported by the gwt-maven-plugin?

See last page of spec: https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0

**Comment by bitwerk** [comment]
Sorry about that, seems to work just fine adding <generateJsInteropExports/> instead of <jsInteropMode>JS_RC</jsInteropMode> in the configuration section.

**Comment by manolo** [comment]
Actually this issue is not fixed yet, <jsInteropMode>JS_RC</jsInteropMode> only when using external JS if you want to export your own java stuff, you need the new flag.
