### ISSUE TITLE
GitHub ribbon on site links to mojo-parent

### ISSUE THREAD

**Issue by tbroyer** [gwt-maven-plugin/gwt-maven-plugin#126]
Everything is in the title.

**Comment by ibaca** [comment]
I'm going to update the project.url from ```<url>http://www.mojohaus.org/gwt-maven-plugin</url>``` to ```<url>https://github.com/gwt-maven-plugin/gwt-maven-plugin</url>```. Is it ok?

**Comment by ibaca** [comment]
This is not necessary to fix this issue, I'm asking because I'm not sure if this change might have other repercussions. Not sure if this is a good idea :weary:.

**Comment by tbroyer** [comment]
FWIW, http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/ has the same issue so I suppose it's a problem in mojo-parent.
The versions-maven-plugin has no ribbon.

**Comment by ibaca** [comment]
Fixed by https://github.com/gwt-maven-plugin/gwt-maven-plugin/commit/bacb641132a4bc2ff9eec98fe647751071bceeb5.
