### ISSUE TITLE
Plugin with version 2.8.0-beta1 continues to use GWT 2.7

### ISSUE THREAD

**Issue by ismagilov** [gwt-maven-plugin/gwt-maven-plugin#128]
It seems that gwt-maven-plugin with version 2.8.0-beta1 continues to use GWT with version 2.7?

Here is meaningful plugin configuration from pom.xml-s.

Parent pom.xml:
```
<dependencies>
    <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt-servlet</artifactId>
        <version>2.8.0-beta1</version>
    </dependency>
    <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt-user</artifactId>
        <version>2.8.0-beta1</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>com.google.gwt.inject</groupId>
        <artifactId>gin</artifactId>
        <version>2.1.2</version>
    </dependency>
    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava-gwt</artifactId>
        <version>19.0</version>
    </dependency>
</dependencies>
```
Child project pom.xml with actual GWT code:
```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <version>2.8.0-beta1</version>
    <configuration>
        <bindAddress>127.0.0.1</bindAddress>
        <logLevel>INFO</logLevel>
        <failOnError>true</failOnError>
        <hostedWebapp>${project.build.directory}/${project.build.finalName}</hostedWebapp>
        <modules>
            <module>...</module>
        </modules>
        <copyWebapp>true</copyWebapp>
        <extraJvmArgs>-Xmx2048M</extraJvmArgs>
        <precompile>false</precompile>
    </configuration>
    <executions>
        <execution>
            <id>gwtcompile</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>compile</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
But when I try to use `<sourceLevel>1.8</sourceLevel>` setting, I get:
```
[INFO] --- gwt-maven-plugin:2.8.0-beta1:compile (gwtcompile) @ hwbs-webapp ---
[ERROR] Source level must be one of [auto, 1.6, 1.7].
[ERROR] Google Web Toolkit 2.7.0
```
Same happens when I use `generateJsInteropExports`. [Added in 2.8.0](https://gwt-maven-plugin.github.io/gwt-maven-plugin/compile-mojo.html#generateJsInteropExports). Actually, I don`t need it, but used to check a version of the underlying GWT.

I have tried to use plugin with version 2.8.0-SNAPSHOT, but got same issue.

**Comment by branflake2267** [comment]
I believe there are too many issues with org.codehaus.mojo:gwt-maven-plugin to continue with it further and not enough support hours to keep it moving forward. I believe the net.ltgt.gwt.maven:gwt-maven-plugin is the wave of the future. :)

**Comment by branflake2267** [comment]
If you need another angle on the new maven plugin, this has it in the pom.xml: https://github.com/branflake2267/Archetypes/blob/master/archetypes/gwt-basic/pom.xml

**Comment by branflake2267** [comment]
Anyway to fix that above, stick the GWT 2.8 dependencies in the plugin itself.

**Comment by ismagilov** [comment]
Do I understand correctly, that `net.ltgt.gwt.maven:gwt-maven-plugin` doesn`t support multiple GWT modules (*.gwt.xml files) in one Maven project? Something similar to 
```
<modules>
  <module>...</module>
</modules>
```
?

**Comment by branflake2267** [comment]
<modules/> comma delimited list should
![Uploading Screen Shot 2015-12-29 at 12.36.28 AM.png…]()
 do the trick.

**Comment by ismagilov** [comment]
> Anyway to fix that above, stick the GWT 2.8 dependencies in the plugin itself.

Same issue, unfortunately:
```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <version>2.8.0-beta1</version>
    <dependencies>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <version>2.8.0-beta1</version>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>2.8.0-beta1</version>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-codeserver</artifactId>
            <version>2.8.0-beta1</version>
        </dependency>
    </dependencies>
    <configuration>
        ...
```
```
[INFO] --- gwt-maven-plugin:2.8.0-beta1:run-codeserver (default-cli) @ hwbs-webapp ---
[ERROR] Source level must be one of [auto, 1.6, 1.7].
[ERROR] Google Web Toolkit 2.7.0
```

**Comment by ismagilov** [comment]
> comma delimited list should ...

Thanks a lot, I will try a trick!

**Comment by branflake2267** [comment]
Oh, use version 2.7.0 for the plugin, and try the sdk version of 2.8.0-beta1 I think.

**Comment by branflake2267** [comment]
By the way, I'm working on the Eclipse integration if that is of interest. The fixes are in snapshot update site.

**Comment by ismagilov** [comment]
> Oh, use version 2.7.0 for the plugin, and try the sdk version of 2.8.0-beta1 I think.

It didn`t help, unfortunately.  Absolutely the same error in stdout. 

> The fixes are in snapshot update site.

Are snapshots published here https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/mojo/gwt-maven-plugin/2.8.0-SNAPSHOT?

Well, keeping in mind the word of owner:
> I believe there are too many issues with org.codehaus.mojo:gwt-maven-plugin to continue with it further and not enough support hours to keep it moving forward.
maybe it is time to switch our project to new plugin... :)

On other hand, this is so strange issue. Plugins pom.xml explicitly state dependency from GWT 2.8.0-beta1. Looks like it is more issue of Maven, then plugin itself?

**Comment by branflake2267** [comment]
I've often blamed it on Maven too. But it's really how the old plugin is doing the job. Thomas has done a far better job on constructing the new plugin. Although I know it's a pain to figure it out, I've been doing that myself too and found it works very good. Once you struggle through the issues, I suspect you'll find it  to do a better job.

**Comment by ibaca** [comment]
Yes, snapshots are deployed to oss.sonatype.org/.../snapshots/. You should have something misconfigured :disappointed:, add your pom and full trace (-X) and we will try to help.

OTOH, I recommend to use the new plugin too. Although I think that the comma separated list of modules in the <modules> config is not what you expect. You can only compile one module per execution, you need to create multiple executions to compile multiple modules. The modules property is used only by codeserver/devmode, but I not not absolutely sure. I'm in favour of multi gwt-module support on the new plugin, but! I also think that this use case is usually for non common situation. In general, you should have one gwt-module per maven-module. Only for curiosity, why you have more than one gwt-module in the same maven-module? (for example I have this multi module situation in a showcase module which has a lot of mini gwt apps to run/test widgets and tools independently)

**Comment by ismagilov** [comment]
@ibaca, thanks!

I have attached pom-s (parent pom and module pom) and `-X` Maven output. I start gwt-codeserver using: `mvn -pl hwbs-webapp clean gwt:run-codeserver`.

By the way, when I use IDEA GWT Super Dev Mode run configuration, everything is started as expected. It takes GWT dependency from pom, but launches it directly, from command line, skipping Maven phases/goals. So used version is correct - 2.8.

[pom-parent.xml.zip](https://github.com/gwt-maven-plugin/gwt-maven-plugin/files/73886/pom-parent.xml.zip)
[gwt-module-pom.xml.zip](https://github.com/gwt-maven-plugin/gwt-maven-plugin/files/73887/gwt-module-pom.xml.zip)
[X-output.txt.zip](https://github.com/gwt-maven-plugin/gwt-maven-plugin/files/73888/X-output.txt.zip)

P.S. The reason of multiple GWT modules presence in one Maven module is fully historical. We understood, that we needed some kind of module separation and created multiple gwt-modules. But the lack of experience stopped us from thinking further and using one maven-module per gwt-module. gwt-maven-module supported multiple `<module>`s and it satisfied us.

**Comment by ibaca** [comment]
As you can see in the X-output, the run-codeserver classpath contains gwt-dev-2.7.0.jar, probably because some of your dependencies has it as a dependency. Use the next command to see which one.
```mvn dependency:tree -Dverbose -Dincludes=:gwt-dev```.

Instead of excluding the gwt dependency from each dependency, I think that you can just add the special BOM dependency as a dependencyManagement in you parent pom and this forces/unify all gwt dependencies. Confirm that all gwt versions are correct with the ``mvn dependency`` plugin.
```
<dependency>
  <groupId>com.google.gwt</groupId>
  <artifactId>gwt</artifactId>
  <version>${gwt.version}</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```

**Comment by ismagilov** [comment]
A little embarrassing, I didn`t look attentively X-output... Yes, your guess was absolutely correct. There was one gwt library that depended on `gwt-dev:2.7`.   

And thanks for a new dependency management way you described. I have already included it into our project and everything works like a charm.

I can`t tell you, how helpful was your advice!.. The issue can be closed.
