### ISSUE TITLE
Line breaks in extraJvmArgs break mojos that launch the shell

### ISSUE THREAD

**Issue by smoyer64** [gwt-maven-plugin/gwt-maven-plugin#133]
Recently my XML code formatter was nice enough to make my XML pretty - the result looked like this:

          <extraJvmArgs>-Xmx2048m -XX:CompileThreshold=7000 -XX:MaxPermSize=512M
            -Derrai.jboss.home=${errai.jboss.home}
            -Derrai.dev.context=${errai.dev.context}</extraJvmArgs>

Looking at the code, I would have expected the spacing to be normalized but this still keeps the shell from launching.

**Comment by ibaca** [comment]
Plexus-utils wasn't doing its work! 😆 This will fix this problem. Anyways, I strongly encourage that you migrate your project to the new [plugin](https://github.com/tbroyer/gwt-maven-plugin) taking as reference this [archetypes](https://github.com/tbroyer/gwt-maven-archetypes) and this [migration guide](https://tbroyer.github.io/gwt-maven-plugin/migrating.html). Thanks!
