### ISSUE TITLE
Remove dependency on GWT Beta 1

### ISSUE THREAD

**Issue by kirillp** [gwt-maven-plugin/gwt-maven-plugin#135]
The latest plugin version has dependency on the  GWT Beta 1
Even if a project is configured to use GWT master or RC, the maven plugin downloads the beta
Please update it to the RC

**Comment by ibaca** [comment]
Already updated, but @kirillp you should know that a new plugin exists which do not depends on specific GWT version, has much better multi-module support, and much more. You should try it out! https://tbroyer.github.io/gwt-maven-plugin/migrating.html
