### ISSUE TITLE
Add a 'tbroyer plugin is now the recommended one' disclaimer

### ISSUE THREAD

**Issue by ibaca** [gwt-maven-plugin/gwt-maven-plugin#137]
**This plugin is not deprecated, but the [tbroyer plugin](https://github.com/tbroyer/gwt-maven-plugin) is a better option and if you [migrate](https://tbroyer.github.io/gwt-maven-plugin/migrating.html) you will get a better development experice.**

The new plugin fixes core problems and nowadays makes no sense to still use this one. Add a...
👎 if you do not want this
👍 if you want to add a message in the doc
🎉 if you want to add a message in maven output console

**Why?** Because having two plugins is confusing for newcomers, even some experienced GWT developers do not know that the new plugin exists and is stable. And, the new plugin promotes correct multi-module configurations, but instead, old plugin (this one) promotes hacking to make it work (requires hacking to make work superdevmode changes detection, which have been ignored because most of the time users end up using IDE launcher). Finally, old plugin is GWT version dependant and do not work well with GWT libs dependencies overrides or exclusions. All this is fixed and improved in the new one! With less and cleaned up code!

So the idea is to make everyone clear than new projects, or projects migrating to GWT 2.8 should make the upgrade to the new plugin.

Personal experience; the new plugin works that well that I do not use IntelliJ Ultimate GWT run configuration anymore. In simple project I just double click the maven goal!, and in complex one I just save the goal to add the `-am -pl :client-module` and maybe some other flags to be more concise. Works perfect! and do not depends on IDE!
![screen shot 2016-07-29 at 16 27 37](https://cloud.githubusercontent.com/assets/1042225/17251565/956286ae-55a9-11e6-9998-57cf005768fa.png)

If you have any complaint or difficulty to make the migration, please add a comment explaining your case. Thanks!

**Comment by ibaca** [comment]
After trying to migrate an errai project to the tbroyer plugin I have conclude one important thing! If you server do not have a multi-module friendly maven plugin, or even worst if your server plugin depends on the devmode server, you better have a monolithic project, and if you have a monolithic project you better use this plugin than the new one because this plugin have all the hacks required to make it work (ironically, all this hacks was the hacks which motivates creating a new plugin).

**Comment by branflake2267** [comment]
I'm all for deprecating this plugin and moving to tbroyers. I'm working on easier integration with the code server launcher on the GWT Eclipse Plugin V3. The code server launcher works best with any server, and DevMode makes it more difficult with about every odd server configuration.

**Comment by ibaca** [comment]
Yep, in some way devmode only make sense if you are using a monolithic approach. Im still using it because of this https://github.com/gwtproject/gwt/issues/9437, but if this is fixed I think that devmode will make no sense anymore. Although I'm not totally sure... actually this kind of force your app to use CORS for developing, and not sure, maybe I'm missing something, what do you think? In this same line of thoughts, the @tbroyer gwt-maven-plugin having a devmode goal is kind of the opposite of the intention of the plugin. Devmode is to run server (jetty) client (codeserver) in the same JVM, but the plugin encourages to run each part independently. Will this https://github.com/gwtproject/gwt/issues/9437 make the devmode goal unnecesary?

If any of this is partially or totally true, may previous comment can be describe as:
* if you want to use devmode use the mojo plugin
* if you want to use codeserver use the tbroyer plugin

**Comment by ibaca** [comment]
![screen shot 2017-04-07 at 19 21 07](https://cloud.githubusercontent.com/assets/1042225/24811703/6ccffa2a-1bc7-11e7-8992-7c24ecb12d38.png)
