### ISSUE TITLE
GWT 2.8.0-RC2 ?

### ISSUE THREAD

**Issue by sblommers** [gwt-maven-plugin/gwt-maven-plugin#139]
Since nobody saying something I'll kick the open door :shipit: what about a release for 2.8.0-RC2 ?

**Comment by ibaca** [comment]
I just released RC2. BUT! 😛 You really should try the new generation of gwt-maven-plugin (https://tbroyer.github.io/gwt-maven-plugin/migrating.html), fixes various core problems, promotes best practices like not-sharing the client and server module (so classpath) wich end up causing lot of problems, and of course, the plugin and GWT do not depends each oder (makings a plugin release without any improvement just to change the version is a pretty bad practice). In any case, this plugin will continue to exist, but if you really want to make thinks right you should try the new generation one 👍 (https://github.com/tbroyer/gwt-maven-plugin).

**Comment by sblommers** [comment]
You are my hero, will definitely check out Browers plugin. Thank you! :dancers:
