### ISSUE TITLE
Confusing page on "productivity tips"

### ISSUE THREAD

**Issue by kmthinkingrock** [gwt-maven-plugin/gwt-maven-plugin#140]
I understand in concept what "hacking the wall in between modules" is supposed to do, but I don't have enough information to practically apply it.

For one, I don't ever use gwt:run and I don't even know what it is or how it differs from gwt:run-codeserver, since there is no more "Dev mode" although I suppose the code for classic dev mode is still around and useful in some cases. Honestly I just ran mvn gwt:run -Pdev and I have no idea what the next step is. Do I use it as a codeserver and run my jetty webserver along side it? Help!

**Comment by ibaca** [comment]
Sorry, I'm not sure what is your doubt. But! most of the hacking required by this plugin is already solved in the new generation of the gwt-maven-plugin (https://tbroyer.github.io/gwt-maven-plugin/migrating.html) which was developed with multi-module setup in mind. You really should try the new one and remove all the hacking in your project setup required by this one.

**Comment by kmthinkingrock** [comment]
I don't know what my doubt is either! but thanks, i'll give that a shot
