### ISSUE TITLE
Style Parameter is missing when using SuperDevmode

### ISSUE THREAD

**Issue by mgoerdes** [gwt-maven-plugin/gwt-maven-plugin#141]
Hi,

with GWT 2.8. the Parameter style is now necessary to activate PRETTY mode when using the super dev mode (https://github.com/gwtproject/gwt/issues/9385). When using gwt-maven-plugin to start the GWT Module in SuperDevMode this style Parameter is not passed to the java execution.

Reduced call with -style PRETTY available in Compile.

-- Compile
/bin/sh -c '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/bin/java' '-Xmx4096m' '-Xss1024k' '-classpath' '...' 'com.google.gwt.dev.Compiler' '-logLevel' 'INFO' '-style' 'PRETTY' '... 'com.bearingpoint.davinci.gui.Banking'

Reduced call with -style PRETTY missing in SuperDevMode
-- SuperDevMode
/bin/sh -c '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/bin/java' '-Xmx4096m' '-Xss1024k' '-Xdebug' '-Xnoagent' '-Djava.compiler=NONE' '-Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y' '-classpath' '...' '-logLevel' 'INFO' '-port' '8888' '-codeServerPort' '9997' '-startupUrl' 'Banking.html' '-nostartServer' '-generateJsInteropExports' '-sourceLevel' 'auto' 'com.bearingpoint.davinci.gui.Banking'

Change should be in to add ".arg("-style", getStyle())" in RunMojo.java (method doExecute).

       cmd.arg( "-war", hostedWebapp.getAbsolutePath() )
            .arg( "-logLevel", getLogLevel() )
            .arg( "-style", getStyle() )
            .arg( "-port", Integer.toString( getPort() ) )
            .arg( "-codeServerPort" , Integer.toString( codeServerPort ))
            .arg( "-startupUrl", getStartupUrl() )
            .arg( noServer, "-nostartServer" )
            .arg( !cacheGeneratorResults, "-XnocacheGeneratorResults" )
            .arg( !superDevMode, "-nosuperDevMode" )
            .arg( !incremental, "-noincremental" )
            .arg( generateJsInteropExports, "-generateJsInteropExports" )

BR,
Mark

**Comment by ibaca** [comment]
GWT parameters depends on the each command and each version, so if you exposes the style to compile/codeserver/devmode it will fail in some versions. This and other problems have been fixed in the new generation of the maven plugin (https://tbroyer.github.io/gwt-maven-plugin/migrating.html) which is stronlgy encouraged to use. 

Please try to migrate your project and ask any doubt, if you have some blocker problem preventing to migrate to the new generation plugin, please comment here so we can improve this situation. If you really cannot migrate will try to find other solution.

**Comment by mgoerdes** [comment]
So is gwt-maven-plugin deprecated now and there will be no future maintenance? As you also added generateJsInteropExports I thought that you still add new features and parameters related to the corresponding GWT version. (gwt-maven-plugin:2.8-rc2 relates to gwt:2.8-rc2).

**Comment by ibaca** [comment]
😛 is not deprecated, but just to not add negative feedback to the GWT community. If you have a critical problem and you really need a fix will fix them, but if you want to make things right, you really should migrate to the new one, the new plugin was rewritten to fix core problems and bad practices, so using this plugin will implain maintain bad practices in your project. There are a lot of projects using this plugin, and most of them use the same version for the GWT lib and this plugin (which make no sense), so we will continue releasing the plugin hoping people will migrate to the new one if the really want. And we will fix any bug or make it minimal changes to make it compatible with the GWT released version.

In any case, probably I end up merging this https://github.com/ibaca/mojo.gwt-maven-plugin/commit/5eb71896e7e7238ef5112907795f82207c7cfa82, this will fix your problem.

**Comment by mgoerdes** [comment]
Great thanks. I temporarily patched it locally and our dev team is enthusiastic. I will also try to move to the new plugin but this could be more work because our project structure is quite complex with more than 35 submodules.
