### ISSUE TITLE
Expose new option -XclosureFormattedOutput

### ISSUE THREAD

**Issue by slavap** [gwt-maven-plugin/gwt-maven-plugin#142]
There is no way to define it now, 
```xml
<configuration>
  <closureFormattedOutput>true</closureFormattedOutput>
</configuration>
```
is not working.

**Comment by ibaca** [comment]
The `-XenableClosureCompiler` option has been removed from GWT, so this cannot be used anymore: https://github.com/gwtproject/gwt/commit/162ccc9c9112a09bf9ea046da95760f5f1886b72

**Comment by slavap** [comment]
NO, NO, NO!
I'm asking about another option, which was added only few months ago. Closure compiler is removed, but you may ask GWT to annotate JS properly for using with external closure compiler.

**Comment by ibaca** [comment]
Which one? 😄, add a link to the GWT issue and will try to add it.

**Comment by slavap** [comment]
-XclosureFormattedOutput

Cannot find issue, but it's here:
https://github.com/gwtproject/gwt/blob/3a41a8067767965ff72f4e49eb015f587fcfee16/dev/codeserver/java/com/google/gwt/dev/codeserver/CompilerOptionsImpl.java

**Comment by slavap** [comment]
And here: https://github.com/gwtproject/gwt/blob/3a41a8067767965ff72f4e49eb015f587fcfee16/dev/core/src/com/google/gwt/dev/util/arg/ArgHandlerClosureFormattedOutput.java

**Comment by ibaca** [comment]
👍 ok, so when you said "no way to define it now" you means "it was never supported", but now that the `enableClosureCompiler` has been removed, you need the other one, correct? Or I'm still missing something 😛?

I'll try to add, but remember that the new generation maven plugin is the recommended one (https://tbroyer.github.io/gwt-maven-plugin/migrating.html) and it does not depends on specific GWT version nor on specific GWT argumeths either! You should try it!

**Comment by slavap** [comment]
You just use https://developers.google.com/closure/compiler/
Then as I understand it you compile with GWT and then postprocess resulting JS with external closure compiler. It works even now with PRETTY style, but with -XclosureFormattedOutput I'm just expecting to get better results. Don't know if it's really working :-)
I will try new maven plugin, thanks for advice! Just afraid it won't work out of the box.
