### ISSUE TITLE
Can not set compiler argument -setPropery

### ISSUE THREAD

**Issue by Xarno** [gwt-maven-plugin/gwt-maven-plugin#143]
My GWT Project uses Gin and therefor needs the setProperty compiler flag: https://github.com/gwtproject/gwt/commit/1d660d2fc00a5cbfeccf512251f78ab4302ab633 to be buildable by GWT 2.8

But the gwt-maven-plugin does not allow to set this Option.

> Google Web Toolkit 2.8.0
> Compiler [-logLevel (ERROR|WARN|INFO|TRACE|DEBUG|SPAM|ALL)] [-workDir dir] [-X[no]closureFormattedOutput] [-[no]compileReport] [-X[no]checkCasts] [-X[no]classMetadata] [-[no]draftCompile] [-[no]checkAssertions] [-XfragmentCount numFragments] [-XfragmentMerge numFragments] [-gen dir] [-[no]generateJsInteropExports] [-XmethodNameDisplayMode (NONE|ONLY_METHOD_NAME|ABBREVIATED|FULL)] [-Xnamespace (NONE|PACKAGE)] [-optimize level] [-[no]saveSource] [-setProperty name=value,value...] [-style (DETAILED|OBFUSCATED|PRETTY)] [-[no]failOnError] [-[no]validateOnly] [-sourceLevel [auto, 1.8]] [-localWorkers count] [-[no]incremental] [-war dir] [-deploy dir] [-extra dir] [-saveSourceOutput dir] module[s] 
> …
>    -setProperty                   Set the values of a property in the form of propertyName=value1[,value2...].

**Comment by ibaca** [comment]
I'll add -setProperty... eventually. In the mean time you can...
* downgrade to GIN 2.1.2
* add this in your `module.gwt.xml`
```xml
<set-configuration-property name="gin.classloading.exceptedPackages" value="com.google.gwt.core.client"/>
```
* migrate to the new generation maven plugin https://tbroyer.github.io/gwt-maven-plugin/migrating.html

**Comment by Xarno** [comment]
Thanks for the answer, i could use the new plugin with the module.gw.xml change.
