### ISSUE TITLE
Unable to mvn gwt:run for the generated artifact

### ISSUE THREAD

**Issue by jhrcek** [gwt-maven-plugin/gwt-maven-plugin#144]
When I generate this artifact using:
```
mvn archetype:generate \
   -DarchetypeGroupId=org.codehaus.mojo \
   -DarchetypeArtifactId=gwt-maven-plugin \
   -DarchetypeVersion=2.8.0
```
and then execute `mvn clean install` and `mvn gwt:run` in the generated project
I get

```
[INFO] --- gwt-maven-plugin:2.8.0:run (default-cli) @ MyApp2 ---
[INFO] create exploded Jetty webapp in /home/hrk/Temp/MyApp2/target/MyApp2-1.0-SNAPSHOT
[ERROR] Source level must be one of [auto, 1.8].
[ERROR] Google Web Toolkit 2.8.0
```

The problem seems to be cause by incorrect minimal version setting here https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/ac86e98739d3afd7d271589b0dfe35a81f9164fc/src/main/archetype/archetype-resources/pom.xml#L18

 - there should be 1.8 instead.

**Comment by ibaca** [comment]
Thanks! but, should note that if you are starting a new gwt maven project you should use this https://github.com/tbroyer/gwt-maven-archetypes/ instead. It uses a new generation plugin which has various advantages. See http://www.g-widgets.com/2016/12/02/gwt-tip-working-with-maven-multi-modules-projects/ and https://www.youtube.com/watch?v=-_YcBeI_Feo&t=207s.
