### ISSUE TITLE
Exception handling for forked tests -- testFailureIgnore

### ISSUE THREAD

**Issue by glucas** [gwt-maven-plugin/gwt-maven-plugin#146]
It seems like testFailureIgnore has no effect for forked test failures. 

Looking at the source I found this:

https://github.com/gwt-maven-plugin/gwt-maven-plugin/blob/ac86e98739d3afd7d271589b0dfe35a81f9164fc/src/main/java/org/codehaus/mojo/gwt/shell/TestMojo.java#L464-L472

A ForkedProcessExecutionxception will be treated as a test failure, while any other exception is treated as a mojo failure and immediately gets propagated. However in practice I see that a test failure results in a JavaCommandException and is always re-thrown as a MojoExecutionException -- I don't see anywhere in the code that ForkedProcessExecutionException is actually thrown.

I may be misunderstanding the intent, but it seems like there is handling here for a test failure counter that is never used?

**Comment by ibaca** [comment]
You are probably right. Looks like the execution of the forked process has been changing but the exception is the same (not totally sure). Anyways, what do you suggest? I almost prefer to deprecate/remove the property which in its own documentation specifies that "its use is not recommended". But right now I'm not sure of the use case of this property. If the tests doesn't work why don't you just skip them. If it randomly fail, you can just ignored them in your CI or whatever. We are open to any suggestion in a form of pull request :wink:.

Also remember that this is a legacy (but supported) plugin, you should use this one (https://github.com/tbroyer/gwt-maven-plugin) for new projects.

**Comment by glucas** [comment]
Thanks for the reply. My current problem is I have a couple GWT unit tests that fail intermittently but only in the CI build -- I was hoping I could continue to run them (so we can investigate further), without having the whole build fail. Not sure I have a suggestion here, but if I come up with something I'll submit a pull request.

We have a fairly big multi-module project using this plugin and are not quite ready to deal with migrating to the new one, but I am keeping an eye on that!

**Comment by ibaca** [comment]
I have applied b62b5a867cc4358b9735a9733c22aa99401ba5f2 to fix for the problem you described. I have removed the non-used ForkedProcessException and use caught JavaCommandException instead.
