### ISSUE TITLE
Aggressive org.eclipse.jetty.util logging with gwt:run-codeserver

### ISSUE THREAD

**Issue by shauntarves** [gwt-maven-plugin/gwt-maven-plugin#147]
I am using gwt-maven-plugin 2.8 and the mvn gwt:run-codeserver command is causing Jetty to log to my terminal at DEBUG level. I've tried everything I can think of to get the log level down (including -Dgwt.logLevel=WARN), but I can't figure out how to quiet it. I didn't have this problem with GWT 2.7, but I suppose there's something I'm missing.

[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ project-xxx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 94 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ project-xxx ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< gwt-maven-plugin:2.8.0:run-codeserver (default-cli) < process-classes @ project-xxx <<<
[INFO] 
[INFO] --- gwt-maven-plugin:2.8.0:run-codeserver (default-cli) @ project-xxx ---
[INFO] Turning off precompile in incremental mode.
[INFO] 13:30:41.323 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
[INFO] 13:30:41.331 [main] INFO org.eclipse.jetty.util.log - Logging initialized @1871ms
[INFO] 13:30:47.249 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - org.eclipse.jetty.server.Server@35d0aad added {qtp1320460618{STOPPED,8<=0<=200,i=0,q=0},AUTO}
[INFO] 13:30:47.259 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - HttpConnectionFactory@73f46fcf{HTTP/1.1} added {HttpConfiguration@3a6f16af{32768/8192,8192/8192,https://:0,[]},POJO}
[INFO] 13:30:47.262 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@2499d1c0{null}{0.0.0.0:0} added {org.eclipse.jetty.server.Server@35d0aad,UNMANAGED}
[INFO] 13:30:47.262 [main] DEBUG org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@2499d1c0{null}{0.0.0.0:0} added {qtp1320460618{STOPPED,8<=0<=200,i=0,q=0},AUTO}
[.......]

**Comment by ibaca** [comment]
Use the property `extraJvmArgs` to add a custom logback configuration, something like `-Dlogback.configurationFile=/home/user/logback.xml`, and a content like:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true">
    <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator" />
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <!-- ALL TRACE DEBUG INFO WARN ERROR OFF -->
    <logger name="com.sun.jersey" level="INFO" />
    <logger name="org.hibernate" level="WARN" />
    <logger name="org.hibernate.SQL" level="WARN" />
    <logger name="org.eclipse.jetty" level="INFO" />

    <root level="WARN">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>
```

**Comment by ibaca** [comment]
uhm... not absolutely sure if it is logback or jul... for jul use:
`-Djava.util.logging.config.file=~/logging.properties`.

**Comment by shauntarves** [comment]
That worked. Thanks!
